language: ruby

cache: bundler

matrix:
  include:
    - rvm: 2.6.5
      script:
        - bundle exec danger
    - rvm: 2.4.0
      env: CONCURRENCY=celluloid-io
    - rvm: 2.4.0
      env: CONCURRENCY=faye-websocket
    - rvm: 2.4.0
      env: CONCURRENCY=async-websocket
    - rvm: 2.6.5
      env: CONCURRENCY=celluloid-io
    - rvm: 2.6.5
      env: CONCURRENCY=faye-websocket
    - rvm: 2.6.5
      env: CONCURRENCY=async-websocket
    - rvm: ruby-head
    - rvm: jruby-head
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
